name: Build Docker Image

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker info
          docker build --no-cache --pull -t izonder/lanny .
      - name: Test the image
        run: |
          docker run --rm izonder/lanny liquibase --version
      - name: Assign the tag
        run: docker tag izonder/lanny izonder/lanny:latest
      - name: Publish the image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push izonder/lanny:latest
